// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/binhbeng/goex/data"
	"github.com/binhbeng/goex/internal/handler"
	"github.com/binhbeng/goex/internal/model"
	"github.com/binhbeng/goex/internal/router"
	"github.com/binhbeng/goex/internal/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewWire() (*router.RouterDeps, error) {
	handlerHandler := handler.NewHandler()
	db, err := data.NewPostgreDB()
	if err != nil {
		return nil, err
	}
	repository := model.NewRepository(db)
	userRepository := model.NewUserRepository(repository)
	client, err := data.NewRedis()
	if err != nil {
		return nil, err
	}
	userService := service.NewUserService(userRepository, client)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	routerDeps := &router.RouterDeps{
		UserHandler: userHandler,
	}
	return routerDeps, nil
}

// wire.go:

var repositorieSet = wire.NewSet(model.NewRepository, model.NewUserRepository)

var serviceSet = wire.NewSet(service.NewUserService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler)

var dataSet = wire.NewSet(data.NewRedis, data.NewPostgreDB)
